stages:
  - test
  - docker

lint:
  stage: test
  image: registry.gitlab.com/etke.cc/base
  script:
    - make lint

unit:
  stage: test
  image: registry.gitlab.com/etke.cc/base
  script:
    - make test
