project_name: ttm
before:
  hooks:
  - go mod tidy

builds:
  - main: ./cmd
    env:
      - CGO_ENABLED=0
    ldflags:
      - -extldflags "-static"
    flags:
      - -tags=timetzdata,goolm
    binary: ttm
    goos:
      - freebsd
      - linux
      - darwin
    goarch:
      - arm64
      - amd64

nfpms:
  - vendor: https://etke.cc
    package_name: time-to-matrix
    maintainer: etke.cc
    description: ttm stand for time-to-matrix, `time`-like program that will send execution info to matrix room
    homepage: https://gitlab.com/etke.cc/ttm
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    file_name_template: "{{ .PackageName }}-{{ .Version }}_{{ .Os }}-{{ .Arch }}"

changelog:
  sort: asc
checksum:
  disable: true
archives:
  - format: binary
